apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.db.host }}
spec:
  ports:
  - name: "{{ .Values.global.db.port }}"
    port: {{ .Values.global.db.port }}
    targetPort: {{ .Values.global.db.port }}
  selector:
    app: airflow
    tier: db