apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgresql-data-claim
  {{- if eq .Values.global.db.storageProvider "ibmcloud" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze"
  labels:
    billingType: "hourly"
    region: us-south
    zone: dal13
  {{- end }}
spec:
  {{ if eq .Values.global.airflow.dag.storageProvider "ibmcloud" }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.global.db.storageSize }}"
  storageClassName: ibmc-file-bronze
  {{ else if eq .Values.global.db.storageProvider "hostpath" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{ end }}
status: {}