apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.redis.host }}
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.global.redis.port }}"
    port: {{ .Values.global.redis.port }}
    targetPort: {{ .Values.global.redis.port }}
  selector:
    app: airflow
    tier: redis
