# Default values for airflow
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tier: worker
replicas: 3
ports:
  logPortName: worker-log-port
  containerLogPort: 8793
  serviceLogPort: 8793