apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow
        role: airflow-app
        tier: {{ .Values.tier }}
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret.name }}
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /dags"]
        volumeMounts:
        - name: dag-persistent-vol
          mountPath: /dags
      containers:
      - name: {{ .Values.tier }}
        image: {{ .Values.global.airflow.image }}:{{ .Values.global.airflow.imageTag }}
        imagePullPolicy: {{ .Values.global.airflow.pullPolicy }}
        args:
          - {{ .Values.tier }}
        env:
        # Airflow settings
        - name: EXECUTOR
          value: {{ .Values.global.airflow.core.executor }}
        - name: FERNET_KEY
          value: "{{ .Values.global.airflow.fernetKey }}"
        - name: LOAD_EX
          value: "{{ .Values.global.airflow.core.load_examples }}"
        - name: WEB_RBAC
          value: "{{ .Values.global.airflow.webrbac }}"
        # DB settings
        - name: POSTGRES_HOST
          value: {{ .Values.global.db.host }}
        - name: POSTGRES_USER
          value: {{ .Values.global.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.global.db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.global.db.database }}
        # Redis settings
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: REDIS_PASSWORD
          value: {{ .Values.global.redis.password }}
        # Rest api settings
        - name: REST_API_TOKEN
          value: {{ .Values.global.airflow.restApiToken }}
        # IBM Cloud settings
        - name: IBMCLOUD_API_KEY
          value: {{ .Values.global.ibmcloud.apiKey }}
        - name: IBMCLOUD_IKS_REGION
          value: {{ .Values.global.ibmcloud.region }}
        - name: KUBE_CLUSTER
          value: {{ .Values.global.ibmcloud.cluster }}
        - name: KUBE_NAMESPACE
          value: {{ .Values.global.ibmcloud.namespace }}
        ports:
        - containerPort: {{ .Values.ports.containerWebPort }}
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.ports.containerWebPort }}
          failureThreshold: 30
          periodSeconds: 20
          timeoutSeconds: 20
          initialDelaySeconds: 60
        volumeMounts:
        - name: dag-persistent-vol
          mountPath: "/usr/local/airflow/dags"
      volumes:
      - name: dag-persistent-vol
        persistentVolumeClaim:
          claimName: dag-volume-claim
      restartPolicy: {{ .Values.global.airflow.restartPolicy }}
status: {}
