apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: "{{ .Values.ports.webPortName }}"
    port: {{ .Values.ports.serviceWebPort }}
    targetPort: {{ .Values.ports.containerWebPort }}
  type: ClusterIP
  selector:
    app: airflow
    tier: {{ .Values.tier }}
