apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.tier }}
spec:
  replicas: {{ .Values.replicas }}
  strategy: {}
  template:
    metadata:
      labels:
        app: airflow
        role: airflow-app
        tier: {{ .Values.tier }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret.name }}
      containers:
      - name: {{ .Values.tier }}
        image: {{ .Values.global.airflow.image }}:{{ .Values.global.airflow.imageTag }}
        imagePullPolicy: {{ .Values.global.airflow.pullPolicy }}
        args:
          - {{ .Values.tier }}
        env:
        - name: NAMESPACE
          value: {{ .Values.global.namespace }}
        # Airflow settings
        - name: FLOWER_PORT
          value: "{{ .Values.ports.containerFlowerPort }}"
        - name: EXECUTOR
          value: {{ .Values.global.airflow.core.executor }}
        # DB settings
        - name: POSTGRES_HOST
          value: {{ .Values.global.db.host }}
        - name: POSTGRES_USER
          value: {{ .Values.global.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.global.db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.global.db.database }}
        # Redis settings
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: REDIS_PASSWORD
          value: {{ .Values.global.redis.password }}
        ports:
        - containerPort: {{ .Values.ports.containerFlowerPort }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.containerFlowerPort }}
          failureThreshold: 30
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 20
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      restartPolicy: {{ .Values.global.airflow.restartPolicy }}

status: {}